name: Build Test - OpenWrt Package

on:
  workflow_dispatch:
    inputs:
      openwrt_version:
        description: 'OpenWrt version to test'
        required: true
        default: 'both'
        type: choice
        options:
        - '23.05'
        - '24.10'
        - 'both'
      verbose:
        description: 'Verbose build output'
        required: false
        default: false
        type: boolean

jobs:
  build-test-23-05:
    name: Build Test - OpenWrt 23.05
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.openwrt_version == '23.05' || github.event.inputs.openwrt_version == 'both' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare package structure
        run: |
          # Create the feed directory structure expected by the action
          mkdir -p feed/gpio-fan-rpm
          # Copy all files to the package directory
          cp -r . feed/gpio-fan-rpm/
          # Remove the feed directory from the package to avoid recursion
          rm -rf feed/gpio-fan-rpm/feed

      - name: Build OpenWrt 23.05 package
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: x86_64-23.05.0
          PACKAGES: gpio-fan-rpm
          V: ${{ github.event.inputs.verbose == 'true' && 's' || '0' }}
          FEED_DIR: ${{ github.workspace }}/feed

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-23.05-packages
          path: bin/packages/x86_64/packages/gpio-fan-rpm_*.ipk

  build-test-24-10:
    name: Build Test - OpenWrt 24.10
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.openwrt_version == '24.10' || github.event.inputs.openwrt_version == 'both' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare package structure
        run: |
          # Create the feed directory structure expected by the action
          mkdir -p feed/gpio-fan-rpm
          # Copy all files to the package directory
          cp -r . feed/gpio-fan-rpm/
          # Remove the feed directory from the package to avoid recursion
          rm -rf feed/gpio-fan-rpm/feed

      - name: Build OpenWrt 24.10 package
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: x86_64-24.10.0
          PACKAGES: gpio-fan-rpm
          V: ${{ github.event.inputs.verbose == 'true' && 's' || '0' }}
          FEED_DIR: ${{ github.workspace }}/feed

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-24.10-packages
          path: bin/packages/x86_64/packages/gpio-fan-rpm_*.ipk 