name: Build OpenWRT Packages and Release

on:
  push:
    tags:
      - '*.*.*-r*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        openwrt_version: [23.05.0, 24.10.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore SDK download cache
        uses: actions/cache@v3
        with:
          path: sdk-cache/${{ matrix.openwrt_version }}
          key: sdk-${{ matrix.openwrt_version }}-cache
          restore-keys: |
            sdk-${{ matrix.openwrt_version }}-cache

      - name: Ensure bin & cache directories and permissions
        run: |
          mkdir -p ${{ github.workspace }}/sdk-cache/${{ matrix.openwrt_version }} && \
          chmod -R a+rwX ${{ github.workspace }}/sdk-cache/${{ matrix.openwrt_version }} && \
          mkdir -p ${{ github.workspace }}/bin/${{ matrix.openwrt_version }} && \
          chmod -R a+rwX ${{ github.workspace }}/bin/${{ matrix.openwrt_version }}

      - name: Build package via OpenWRT SDK
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/sdk-cache/${{ matrix.openwrt_version }}:/downloads \
            -v ${{ github.workspace }}/bin/${{ matrix.openwrt_version }}:/builder/bin \
            --platform linux/amd64 \
            openwrt/sdk:x86-64-${{ matrix.openwrt_version }} \
            bash -eo pipefail -c '
              if [ -f ./setup.sh ]; then ./setup.sh; fi && \
              git clone --depth 1 --branch ${{ github.ref_name }} https://github.com/${{ github.repository }}.git package/gpio-fan-rpm && \
              ./scripts/feeds update -a && \
              ./scripts/feeds install libgpiod libjson-c && \
              make defconfig && \
              make package/gpio-fan-rpm/download && \
              make package/gpio-fan-rpm/prepare && \
              make -j$(nproc) package/gpio-fan-rpm/compile'

      - name: Save SDK download cache
        uses: actions/cache@v3
        with:
          path: sdk-cache/${{ matrix.openwrt_version }}
          key: sdk-${{ matrix.openwrt_version }}-cache

      - name: Prepare Release Assets
        id: prep_assets
        run: |
          SHORT_VER=$(echo "${{ matrix.openwrt_version }}" | awk -F. '{print $1"."$2}')
          TARGET_DIR="${{ github.workspace }}/bin/${SHORT_VER}"
          mkdir -p "$TARGET_DIR"
          IPK_FILE=$(find ${{ github.workspace }}/bin/${{ matrix.openwrt_version }} -name "gpio-fan-rpm*_all.ipk" | head -n1)
          if [[ -z "$IPK_FILE" ]]; then 
            echo "IPK file not found" >&2
            exit 1
          fi
          cp "$IPK_FILE" "$TARGET_DIR/"
          echo "package_asset=$TARGET_DIR/$(basename "$IPK_FILE")" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          body: |
            gpio-fan-rpm ${{ github.ref_name }} release for OpenWRT

            ## Supported Versions
            - OpenWRT 23.05 (libgpiod v1)
            - OpenWRT 24.10 (libgpiod v2)

            ## Features
            - Measures fan RPM using GPIO edge detection
            - Supports both libgpiod v1 and v2 APIs
            - Multiple output formats (plain, JSON, collectd)
          draft: true
          prerelease: false
          files: |
            ${{ steps.prep_assets.outputs.package_asset }}
        env:
          GITHUB_TOKEN: ${{ secrets.OWRT_PACKAGE_RELEASE_TOKEN }}
