name: Test workflow

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Test action
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Create Release
        run: |
          echo "Test"
      - name: Install apk-tools (for reading .apk metadata)
        run: |
          sudo wget -qO /usr/local/bin/apk \
            https://gitlab.alpinelinux.org/api/v4/projects/5/packages/generic/v3.0.6/x86_64/apk.static
          sudo chmod +x /usr/local/bin/apk
          apk --version
